const money=(v)=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:2});
const date=(v)=>v?new Date(`${String(v).slice(0,10)}T00:00:00`).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}).replace(/ /g,"-"):"-";
const balance=(v)=>{const n=Number(v||0);return `${money(Math.abs(n))}${n?` ${n<0?"Cr":"Dr"}`:""}`};
export default function StatementPaper({data,type}){const customer=type==="customer",party=data?.party||{},totals=data?.totals||{},period=data?.period||{},rows=Array.isArray(data?.rows)?data.rows:[],name=party[customer?"customer_name":"supplier_name"]||"-",from=period.date_from?date(period.date_from):rows[0]?.date?date(rows[0].date):"Beginning",to=period.date_to?date(period.date_to):rows.at(-1)?.date?date(rows.at(-1).date):"Present",range=period.full_statement?`${from} - ${to}`:`${from} - ${to}`;return <article className="statement-paper bg-white font-sans text-[#111827]">
<div className="statement-title"><h1>{customer?"Customer":"Supplier"} Statement</h1><div className="statement-contact">TexTradeOS PRO · Business Account Management System</div><div className="statement-period">Date: {range}</div></div>
<div className="statement-summary"><div><span>Account</span><strong>{name}</strong><small>{[party.person_name,party.city,party.address].filter(Boolean).join(" | ")||"Account details"}</small></div><div className="statement-summary-values"><p><span>Opening Balance</span><b>{balance(data?.opening_balance)}</b></p><p><span>Total {customer?"Bill":"Purchase"}</span><b>{money(totals.debit)}</b></p><p><span>Total Credit</span><b>{money(totals.credit)}</b></p><p className="closing"><span>Closing Balance</span><b>{balance(data?.closing_balance)}</b></p></div></div>
<table className="statement-ledger"><colgroup><col className="no"/><col className="date"/><col className="ref"/><col className="method"/><col className="desc"/><col className="bill"/><col className="payment"/><col className="balance"/></colgroup><thead><tr><th>#</th><th>Date</th><th>Reff. No.</th><th>Method</th><th>Description</th><th>{customer?"Bill":"Purchase"}</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={`${r.type}-${r.id}-${i}`} className="statement-row"><td>{i+1}.</td><td>{date(r.date)}</td><td><b>{r.reference||"-"}</b>{r.reference_no&&r.reference_no!==r.reference&&<small>{r.reference_no}</small>}</td><td>{methodOf(r)}</td><td><b>{r.description||"Transaction"}</b>{detailsOf(r)&&<small>{detailsOf(r)}</small>}{r.notes&&<small>{r.notes}</small>}</td><td className="num">{r.debit?money(r.debit):"0.0"}</td><td className="num">{r.credit?money(r.credit):"0.0"}</td><td className="num strong">{balance(r.running_balance)}</td></tr>):<tr><td colSpan="8" className="empty">No transactions found for this period.</td></tr>}</tbody></table>
<div className="statement-final"><div/><div><p><span>Opening Balance</span><b>{balance(data?.opening_balance)}</b></p><p><span>Total {customer?"Bill":"Purchase"}</span><b>{money(totals.debit)}</b></p><p><span>Total Credit</span><b>{money(totals.credit)}</b></p><p className="closing"><span>Closing Balance</span><b>{balance(data?.closing_balance)}</b></p></div></div>
<footer className="statement-footer"><span>Powered by SparkPair © {new Date().getFullYear()}</span><strong>TexTradeOS PRO by SparkPair</strong></footer>
</article>}
function methodOf(r){if(r.method)return String(r.method).replace(/_/g," ");const d=String(r.description||"").toLowerCase();if(d.includes("return"))return "Adjustment";if(d.includes("invoice"))return "Invoice";if(d.includes("purchase"))return "Purchase";return "Entry"}
function detailsOf(r){return [r.total_pcs!=null&&`PCs: ${r.total_pcs}`,r.article_count!=null&&`Articles: ${r.article_count}`,r.packet_count!=null&&`Packets: ${r.packet_count}`].filter(Boolean).join(" · ")}
