import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Edit3, Plus, RotateCcw, Save, ScanLine, Trash2 } from "lucide-react";
import { v4 as uuidv4 } from "uuid";
import Modal from "../Modal";
import Button from "../Button";
import Input from "../Input";
import Select from "../Select";
import { SectionHeader } from "../SectionHeader";
import { fetchMyInvoiceCounter } from "../../api/business";
import { fetchSalesReturnable } from "../../api/returns.api";
import { createCustomer, fetchCustomers, fetchInventory } from "../../api/commerce";
import { useToast } from "../../context/ToastContext";
import { InvoicePrintPreview } from "./InvoicePreviewModal";
import ReturnEditor, { returnTotals } from "../Returns/ReturnEditor";
import PaymentEditor from "./PaymentEditor";
import Checkbox from "../Checkbox";
import CustomerFormModal from "../User/CustomerFormModal";
import InvoiceScanModal, { unlockScanAudio } from "../Scanner/InvoiceScanModal";
import { motion } from "framer-motion";

const todayInput = () => {
  const date = new Date();
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
};

const numberValue = (value) => {
  const parsed = Number(String(value ?? "").replace(/,/g, ""));
  return Number.isFinite(parsed) ? parsed : 0;
};

const capitalizeWords = (value) => String(value ?? "").toLowerCase().replace(/\s+/g, " ").replace(/\b\w/g, (character) => character.toUpperCase());
const formatInvoiceNumber = (year, nextInvoiceNo) => `${year}-${String(Math.max(1, Number(nextInvoiceNo) || 1)).padStart(4, "0")}`;
const toInvoiceInventory = (items = []) => items.map((item) => ({ ...item, value: item.article_no, stock_pcs: Math.max(0, numberValue(item.stock_pcs ?? item.available_pcs)), label: `${item.article_no} | ${item.description || "Article"} | Stock ${Math.max(0, numberValue(item.stock_pcs ?? item.available_pcs))} pcs | Sale ${item.sale_rate || item.rate || 0}` })).filter((item) => item.stock_pcs > 0);
const newInvoiceArticle = (item) => ({ _key: uuidv4(), article_no: item.article_no, purchase_number: item.purchase_number, description: item.description || "", size: item.size || "", unit: numberValue(item.unit), quantity_pkt: "", dzn: "", pcs: "", purchase_rate: numberValue(item.rate), rate: numberValue(item.sale_rate || item.rate), discount: item.discount || "" });
const syncQuantity = (row, field, value) => { const unit=Math.max(0,numberValue(field==="unit"?value:row.unit)); const next={...row,[field]:value}; if(field==="quantity_pkt"){const pcs=numberValue(value)*unit;next.pcs=pcs?String(pcs):"";next.dzn=pcs?String(pcs/12):"";} if(field==="dzn"){const pcs=numberValue(value)*12;next.pcs=pcs?String(pcs):"";next.quantity_pkt=unit?String(pcs/unit):"";} if(field==="pcs"){const pcs=numberValue(value);next.dzn=pcs?String(pcs/12):"";next.quantity_pkt=unit?String(pcs/unit):"";} return next; };
const discountDetails=(discount,pcs,rate)=>{const raw=String(discount||"").trim();if(!raw)return{amount:0,type:""};const pieces=Math.max(0,numberValue(pcs)),unitRate=Math.max(0,numberValue(rate));if(!pieces||!unitRate)return{amount:0,type:raw.endsWith("%")?"percent":"rupee"};if(raw.endsWith("%")){const percentage=Math.min(100,Math.max(0,numberValue(raw.slice(0,-1))));return{amount:pieces*(unitRate*percentage/100),type:"percent"};}const perPiece=Math.min(unitRate,Math.max(0,numberValue(raw)));return{amount:pieces*perPiece,type:"rupee"};};
const calculateArticle=(row)=>{const dzn=numberValue(row.dzn),pcs=numberValue(row.pcs),rate=numberValue(row.rate),gross=pcs*rate,discount=discountDetails(row.discount,pcs,rate),discountAmount=Math.min(gross,discount.amount);return{...row,dzn,pcs,quantity_pkt:numberValue(row.quantity_pkt),rate,gross_amount:gross,discount_type:discount.type,discount_amount:discountAmount,amount:Math.max(0,gross-discountAmount)};};
const calculateInvoiceTotals=(rows,salesReturnAmount=0,receivedAmount=0)=>{const gross_amount=rows.reduce((s,r)=>s+Number(r.gross_amount||0),0),percent_discount_amount=rows.reduce((s,r)=>s+(r.discount_type==="percent"?Number(r.discount_amount||0):0),0),rupee_discount_amount=rows.reduce((s,r)=>s+(r.discount_type==="rupee"?Number(r.discount_amount||0):0),0),total_discount_amount=percent_discount_amount+rupee_discount_amount,net_amount=Math.max(0,gross_amount-total_discount_amount),sales_return_amount=Math.min(net_amount,Math.max(0,numberValue(salesReturnAmount))),total_amount=Math.max(0,net_amount-sales_return_amount),received_amount=Math.max(0,numberValue(receivedAmount));return{gross_amount,percent_discount_amount,rupee_discount_amount,total_discount_amount,net_amount,sales_return_amount,received_amount,total_amount,balance_amount:Math.max(0,total_amount-received_amount),return_amount:Math.max(0,received_amount-total_amount)};};

function InvoiceItemModal({isOpen,onClose,onSubmit,article=null,inventory=[]}){const[selectedArticleNo,setSelectedArticleNo]=useState("");const[row,setRow]=useState(null);const[error,setError]=useState("");useEffect(()=>{if(!isOpen)return;setError("");if(article){setSelectedArticleNo(article.article_no);setRow(article);}else{setSelectedArticleNo("");setRow(null);}},[article,inventory,isOpen]);const selectedArticle=inventory.find(i=>i.article_no===selectedArticleNo);const chooseArticle=(no)=>{const match=inventory.find(i=>i.article_no===no);setSelectedArticleNo(no);setRow(match?newInvoiceArticle(match):null);};const update=(field,value)=>setRow(prev=>{if(!prev)return prev;if(["quantity_pkt","dzn","pcs"].includes(field)){const next=syncQuantity(prev,field,value),available=numberValue(selectedArticle?.stock_pcs);if(numberValue(next.pcs)>available){setError(`Only ${available} pieces are available.`);return syncQuantity(prev,"pcs",String(available));}setError("");return next;}return{...prev,[field]:value};});const submit=(e)=>{e.preventDefault();if(!row?.article_no)return setError("Select an article first.");if(numberValue(row.pcs)<=0)return setError("Enter quantity.");if(numberValue(row.pcs)>numberValue(selectedArticle?.stock_pcs))return setError(`Only ${numberValue(selectedArticle?.stock_pcs)} pieces are available.`);onSubmit(calculateArticle(row));};return <Modal isOpen={isOpen} onClose={onClose} maxWidth="max-w-3xl" title={article?"Edit Invoice Item":"Add Invoice Item"} subtitle="Select the item and enter its sale quantity" footer={<div className="flex w-full items-center justify-between"><p className="text-xs font-medium text-red-600">{error}</p><div className="flex gap-3"><Button outline variant="secondary" onClick={onClose}>Discard</Button><Button icon={Save} onClick={submit}>{article?"Save Item":"Add Item"}</Button></div></div>}><form onSubmit={submit} className="grid grid-cols-1 gap-3.5 p-0.5 md:grid-cols-3"><div className="md:col-span-3"><Select label="Search & Select Article" value={selectedArticleNo} onChange={chooseArticle} options={inventory} placeholder="Choose article by number or description" /></div><Input label="Packets" type="number" min="0" value={row?.quantity_pkt||""} onChange={e=>update("quantity_pkt",e.target.value)}/><Input label="Dozens" type="number" min="0" value={row?.dzn||""} onChange={e=>update("dzn",e.target.value)}/><Input label="Pieces" type="number" min="0" value={row?.pcs||""} onChange={e=>update("pcs",e.target.value)}/><Input label="Sale Rate" type="number" min="0" value={row?.rate||""} onChange={e=>update("rate",e.target.value)}/><Input label="Discount" value={row?.discount||""} onChange={e=>update("discount",e.target.value)} required={false}/><Input label="Amount" value={row?calculateArticle(row).amount.toFixed(2):"0.00"} disabled/><button type="submit" className="hidden" /></form></Modal>;}

export default function InvoiceFormModal({isOpen,onClose,onAction}){const{showToast}=useToast();const[step,setStep]=useState("entry"),[entryStage,setEntryStage]=useState(1),[customerId,setCustomerId]=useState(""),[customerMode,setCustomerMode]=useState("registered"),[quickCustomerOpen,setQuickCustomerOpen]=useState(false),[walkIn,setWalkIn]=useState({customer_name:"Walk-in Customer",person_name:"",urdu_title:"",phone_number:"",address:"",city:""}),[customers,setCustomers]=useState([]),[salesmanName,setSalesmanName]=useState(""),[articles,setArticles]=useState([]),[inventory,setInventory]=useState([]),[itemModal,setItemModal]=useState({isOpen:false,article:null}),[scanModalOpen,setScanModalOpen]=useState(false),[salesReturnRows,setSalesReturnRows]=useState([]),[includeSalesReturn,setIncludeSalesReturn]=useState(false),[returnAdjustment,setReturnAdjustment]=useState({type:"none",value:""}),[payment,setPayment]=useState({received_now:false,amount:"",method:"cash"}),[invoiceNumber,setInvoiceNumber]=useState(""),[submitting,setSubmitting]=useState(false),[loadingData,setLoadingData]=useState(false),[error,setError]=useState("");
useEffect(()=>{if(!isOpen)return;let cancelled=false;setStep("entry");setEntryStage(1);setCustomerId("");setCustomerMode("registered");setQuickCustomerOpen(false);setWalkIn({customer_name:"Walk-in Customer",person_name:"",urdu_title:"",phone_number:"",address:"",city:""});setSalesmanName("");setArticles([]);setSalesReturnRows([]);setIncludeSalesReturn(false);setReturnAdjustment({type:"none",value:""});setPayment({received_now:false,amount:"",method:"cash"});setError("");setLoadingData(true);Promise.all([fetchCustomers(),fetchInventory(),fetchMyInvoiceCounter({year:new Date().getFullYear()})]).then(([customerRows,inventoryRows,counter])=>{if(cancelled)return;setCustomers((Array.isArray(customerRows)?customerRows:[]).filter(c=>c.isActive!==false));setInventory(toInvoiceInventory(Array.isArray(inventoryRows)?inventoryRows:[]));setInvoiceNumber(formatInvoiceNumber(counter?.year||new Date().getFullYear(),counter?.next_invoice_no||1));}).catch(err=>{if(!cancelled){setCustomers([]);setInventory([]);setError(err?.response?.data?.message||"Could not load invoice data from the server.");}}).finally(()=>{if(!cancelled)setLoadingData(false);});return()=>{cancelled=true;};},[isOpen]);
const calculatedArticles=useMemo(()=>articles.map(calculateArticle),[articles]);const itemInventory=useMemo(()=>inventory.map(item=>{const used=articles.reduce((s,r)=>r.article_no===item.article_no&&r._key!==itemModal.article?._key?s+numberValue(r.pcs):s,0),stock=Math.max(0,numberValue(item.stock_pcs)-used);return{...item,stock_pcs:stock,label:`${item.article_no} | ${item.description||"Article"} | Available ${stock} pcs | Sale ${item.sale_rate||item.rate||0}`};}).filter(i=>i.stock_pcs>0||i.article_no===itemModal.article?.article_no),[articles,inventory,itemModal.article]);const scanInventory=useMemo(()=>inventory.map(item=>({...item,stock_pcs:Math.max(0,numberValue(item.stock_pcs)-articles.reduce((s,r)=>r.article_no===item.article_no?s+numberValue(r.pcs):s,0))})).filter(i=>i.stock_pcs>0),[articles,inventory]);const[salesReturnInventory,setSalesReturnInventory]=useState([]),[salesReturnLoading,setSalesReturnLoading]=useState(false);
useEffect(()=>{let cancelled=false;if(!customerId||customerMode!=="registered"){setSalesReturnInventory([]);return;}setSalesReturnLoading(true);fetchSalesReturnable(customerId).then(items=>{if(!cancelled)setSalesReturnInventory(Array.isArray(items)?items:[]);}).catch(err=>{if(!cancelled){setSalesReturnInventory([]);setError(err?.response?.data?.message||"Could not load returnable articles for this customer.");}}).finally(()=>{if(!cancelled)setSalesReturnLoading(false);});return()=>{cancelled=true;};},[customerId,customerMode]);
const salesReturnTotals=useMemo(()=>returnTotals(salesReturnRows,returnAdjustment),[salesReturnRows,returnAdjustment]);const invoiceTotals=useMemo(()=>calculateInvoiceTotals(calculatedArticles,salesReturnTotals.amount,payment.received_now?payment.amount:0),[calculatedArticles,salesReturnTotals.amount,payment]);const selectedCustomer=useMemo(()=>customerMode==="walkin"?{_id:"",...walkIn,customer_name:walkIn.customer_name.trim()||"Walk-in Customer",isWalkIn:true}:customers.find(c=>c._id===customerId)||null,[customerId,customerMode,customers,walkIn]);const customerOptions=useMemo(()=>customers.map(c=>({label:c.customer_name,value:c._id})),[customers]);const draftInvoice=useMemo(()=>({invoice_number:invoiceNumber,invoice_date:todayInput(),customer_id:selectedCustomer?._id||"",customer_name:selectedCustomer?.customer_name||"",customer_urdu_title:selectedCustomer?.urdu_title||"",salesman_name:salesmanName.trim(),customer_phone:selectedCustomer?.phone_number||"",customer_address:selectedCustomer?.address||"",articles:calculatedArticles,sales_return:{articles:salesReturnRows,adjustment:returnAdjustment,total_pcs:salesReturnTotals.pcs,gross_amount:salesReturnTotals.gross,adjustment_amount:salesReturnTotals.adjustment,total_amount:salesReturnTotals.amount},payment:{...payment,amount:payment.received_now?numberValue(payment.amount):0},...invoiceTotals}),[invoiceNumber,selectedCustomer,salesmanName,calculatedArticles,salesReturnRows,returnAdjustment,salesReturnTotals,payment,invoiceTotals]);
const handleQuickCustomerCreate=async(payload)=>{try{const created=await createCustomer(payload);const rows=await fetchCustomers();setCustomers((Array.isArray(rows)?rows:[]).filter(c=>c.isActive!==false));setCustomerMode("registered");setCustomerId(created._id);setQuickCustomerOpen(false);showToast({type:"success",message:`${created.customer_name} added and selected.`});return created;}catch(err){const message=err?.response?.data?.message||"Failed to add customer";showToast({type:"error",message});throw err;}};const upsertArticle=(article)=>{setArticles(rows=>{const index=rows.findIndex(r=>r._key===article._key);if(index>=0)return rows.map(r=>r._key===article._key?article:r);const duplicate=rows.findIndex(r=>r.article_no===article.article_no);if(duplicate>=0)return rows.map((r,i)=>i===duplicate?calculateArticle(syncQuantity(r,"pcs",String(numberValue(r.pcs)+numberValue(article.pcs)))):r);return[...rows,article];});setItemModal({isOpen:false,article:null});};const mergeScannedRows=(incoming)=>{incoming.forEach(upsertArticle);setScanModalOpen(false);};const removeRow=(key)=>setArticles(rows=>rows.filter(r=>r._key!==key));
const advance=()=>{if(entryStage===1&&!selectedCustomer)return setError("Select a customer to continue.");if(entryStage===1&&!salesmanName.trim())return setError("Enter the salesperson name to continue.");if(entryStage===2&&!calculatedArticles.length)return setError("Add at least one article to continue.");setError("");setEntryStage(s=>Math.min(3,s+1));};const review=()=>{if(!selectedCustomer)return setError("Select a customer.");if(!salesmanName.trim())return setError("Salesman name is required.");if(!calculatedArticles.length)return setError("Add at least one article.");const over=calculatedArticles.find(r=>numberValue(r.pcs)>numberValue(inventory.find(i=>i.article_no===r.article_no)?.stock_pcs));if(over)return setError(`${over.article_no}: only ${numberValue(inventory.find(i=>i.article_no===over.article_no)?.stock_pcs)} pieces are available.`);setError("");setStep("preview");};const save=async()=>{setSubmitting(true);try{await onAction(draftInvoice);onClose();}catch(err){const message=err?.response?.data?.message||"Failed to save invoice";setError(message);showToast({type:"error",message});}finally{setSubmitting(false);}};
return <Modal isOpen={isOpen} onClose={onClose} title={step==="entry"?"New Sales Invoice":"Review Sales Invoice"} subtitle={step==="entry"?`Invoice ${invoiceNumber||"..."} · Complete the 3 simple sections below`:"Check customer, items and payment before saving"} maxWidth="max-w-5xl" closeOnEscape={!quickCustomerOpen} footer={<div className="flex w-full items-center justify-between gap-3"><p className="text-xs font-medium text-red-600">{error}</p><div className="flex gap-2">{step==="preview"?<><Button variant="secondary" outline icon={ArrowLeft} onClick={()=>setStep("entry")} disabled={submitting}>Back</Button><Button icon={Save} onClick={save} loading={submitting}>Save Invoice</Button></>:<>{entryStage>1&&<Button variant="secondary" outline icon={ArrowLeft} onClick={()=>setEntryStage(s=>s-1)}>Back</Button>}{entryStage<3?<Button icon={ArrowRight} iconPosition="right" onClick={advance} disabled={loadingData}>Continue</Button>:<Button icon={ArrowRight} iconPosition="right" onClick={review} disabled={loadingData}>Review Invoice</Button>}</>}</div></div>}>
{step==="preview"?<InvoicePrintPreview invoice={draftInvoice} businessName="Akhlaq Garments" printMode="a5"/>:<div className="grid gap-5 p-0.5"><div className="grid grid-cols-3 overflow-hidden rounded-xl border border-gray-200 bg-gray-50 text-center text-xs font-semibold"><button type="button" onClick={()=>setEntryStage(1)} className="px-3 py-2.5">1 · Customer</button><button type="button" disabled={entryStage<2} onClick={()=>setEntryStage(2)} className="px-3 py-2.5">2 · Items</button><button type="button" disabled={entryStage<3} onClick={()=>setEntryStage(3)} className="px-3 py-2.5">3 · Payment</button></div>{loadingData&&<p className="rounded-xl border border-gray-200 bg-gray-50 p-3 text-sm text-gray-500">Loading customers and inventory from server...</p>}
<section className={entryStage===1?"block":"hidden"}><SectionHeader step="1" title="Who is buying?" subtitle="Select the customer and salesperson handling this sale"/><div className="mb-3 flex gap-2"><Button size="sm" outline onClick={()=>setCustomerMode("registered")}>Registered</Button><Button size="sm" outline onClick={()=>{setCustomerMode("walkin");setCustomerId("");setIncludeSalesReturn(false);setSalesReturnRows([]);}}>Walk-in</Button>{customerMode==="registered"&&<Button size="sm" outline icon={Plus} onClick={()=>setQuickCustomerOpen(true)}>Quick Add Customer</Button>}</div><div className="grid gap-3 md:grid-cols-2">{customerMode==="registered"?<Select label="Customer *" value={customerId} onChange={setCustomerId} options={customerOptions} placeholder="Choose customer"/>:<Input label="Customer Name" value={walkIn.customer_name} onChange={e=>setWalkIn(w=>({...w,customer_name:e.target.value}))}/>}<Input label="Salesperson *" value={salesmanName} onChange={e=>setSalesmanName(capitalizeWords(e.target.value))}/></div>{selectedCustomer&&customerMode==="registered"&&<div className="mt-3 rounded-xl border border-gray-300 bg-gray-50 p-3 text-xs text-gray-600">{selectedCustomer.person_name||"-"} · {selectedCustomer.phone_number||"-"} · {selectedCustomer.city||"-"}</div>}</section>
<section className={entryStage===2?"block":"hidden"}><SectionHeader step="2" title="Invoice Items" subtitle={`${calculatedArticles.length} items added`} right={<div className="flex gap-2"><Button size="sm" outline icon={ScanLine} onClick={async()=>{await unlockScanAudio().catch(()=>false);setScanModalOpen(true);}}>Scan QR</Button><Button size="sm" icon={Plus} onClick={()=>setItemModal({isOpen:true,article:null})}>Add Item</Button></div>}/><div className="overflow-x-auto rounded-xl border border-gray-300"><table className="w-full"><thead><tr className="bg-gray-50 text-xs text-gray-500"><th className="p-3 text-left">Article</th><th>Pieces</th><th>Rate</th><th>Amount</th><th/></tr></thead><tbody>{calculatedArticles.length?calculatedArticles.map(a=><tr key={a._key} className="border-t"><td className="p-3"><b>{a.article_no}</b><div className="text-xs text-gray-500">{a.description}</div></td><td className="text-center">{a.pcs}</td><td className="text-center">{a.rate.toFixed(2)}</td><td className="text-center">{a.amount.toFixed(2)}</td><td><button onClick={()=>setItemModal({isOpen:true,article:a})}><Edit3 className="h-4 w-4"/></button><button onClick={()=>removeRow(a._key)}><Trash2 className="h-4 w-4"/></button></td></tr>):<tr><td colSpan="5" className="p-8 text-center text-sm text-gray-400">No items added.</td></tr>}</tbody></table></div></section>
<section className={entryStage===3?"block":"hidden"}><SectionHeader step="3" title="Return & Payment" subtitle="Record return and payment"/><div className="rounded-xl border border-gray-300"><div className="flex justify-between bg-gray-50 p-4"><span>Sales Return with this Invoice</span>{customerMode==="registered"&&<Checkbox checked={includeSalesReturn} onChange={checked=>{setIncludeSalesReturn(checked);if(!checked)setSalesReturnRows([]);}} label="Add return"/>}</div>{includeSalesReturn&&<div className="p-4"><ReturnEditor inventory={salesReturnInventory} rows={salesReturnRows} onChange={setSalesReturnRows} adjustment={returnAdjustment} onAdjustmentChange={setReturnAdjustment} subtitle={salesReturnLoading?"Loading...":"Customer sold articles"}/></div>}</div><div className="mt-4"><PaymentEditor payment={payment} onChange={setPayment}/></div><div className="mt-4 rounded-xl bg-gray-50 p-4 text-sm">Payable: <b>{invoiceTotals.total_amount.toFixed(2)}</b> · Received: <b>{invoiceTotals.received_amount.toFixed(2)}</b> · Balance: <b>{invoiceTotals.balance_amount.toFixed(2)}</b></div></section></div>}
<InvoiceItemModal isOpen={itemModal.isOpen} article={itemModal.article} inventory={itemInventory} onClose={()=>setItemModal({isOpen:false,article:null})} onSubmit={upsertArticle}/><InvoiceScanModal isOpen={scanModalOpen} inventory={scanInventory} onClose={()=>setScanModalOpen(false)} onApply={mergeScannedRows}/><CustomerFormModal isOpen={quickCustomerOpen} onClose={()=>setQuickCustomerOpen(false)} onSubmit={handleQuickCustomerCreate}/></Modal>;
}
