import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, FileDown, FileText, Loader2, Printer, Search } from "lucide-react";
import PageHeader from "../components/PageHeader";
import Button from "../components/Button";
import StatementPaper from "../components/Reports/StatementPaper";
import { fetchCustomers, fetchCustomerStatement, fetchSuppliers, fetchSupplierStatement } from "../api/commerce";

const money=(v)=>`Rs ${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
export default function Reports(){
 const [category,setCategory]=useState("customer"),[parties,setParties]=useState([]),[partyId,setPartyId]=useState(""),[dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState(""),[data,setData]=useState(null),[loading,setLoading]=useState(false),[partiesLoading,setPartiesLoading]=useState(false),[error,setError]=useState(""); const paperRef=useRef(null);
 useEffect(()=>{let live=true;const loadParties=async()=>{setPartiesLoading(true);setPartyId("");setData(null);setError("");try{const rows=category==="customer"?await fetchCustomers():await fetchSuppliers();if(live)setParties(Array.isArray(rows)?rows:[])}catch(e){if(live){setParties([]);setError(e?.response?.data?.message||e?.message||"Could not load accounts")}}finally{if(live)setPartiesLoading(false)}};loadParties();return()=>{live=false}},[category]);
 const selected=useMemo(()=>parties.find(p=>String(p._id)===String(partyId)),[parties,partyId]);
 const generate=async()=>{if(!partyId){setError(`Select a ${category} first`);return}if(dateFrom&&dateTo&&dateFrom>dateTo){setError("From date cannot be after To date");return}setLoading(true);setError("");try{const params={};if(dateFrom)params.date_from=dateFrom;if(dateTo)params.date_to=dateTo;setData(await(category==="customer"?fetchCustomerStatement(partyId,params):fetchSupplierStatement(partyId,params)))}catch(e){setData(null);setError(e?.response?.data?.message||e?.message||"Could not generate statement")}finally{setLoading(false)}};
 const print=()=>{if(!data)return;window.print()}; const exportPdf=()=>{if(!data)return;window.print()};
 return <div className="reports-page relative z-10 mx-auto flex h-full max-w-7xl flex-col"><PageHeader title="Reporting" subtitle="Generate detailed customer and supplier account statements."/>
  <div className="min-h-0 flex-1 overflow-auto pb-8"><section className="rounded-3xl border border-gray-300 bg-white p-5 sm:p-6"><div className="mb-5"><p className="text-sm font-bold text-gray-900">Statement Report</p><p className="mt-1 text-xs text-gray-500">Choose an account and optional date range. Leave dates empty for the complete statement.</p></div><div className="grid gap-4 lg:grid-cols-[180px_1fr_180px_180px_auto]"><Field label="Category"><select value={category} onChange={e=>setCategory(e.target.value)} className="report-input"><option value="customer">Customer</option><option value="supplier">Supplier</option></select></Field><Field label={category==="customer"?"Customer":"Supplier"}><select value={partyId} disabled={partiesLoading} onChange={e=>{setPartyId(e.target.value);setData(null)}} className="report-input"><option value="">{partiesLoading?"Loading...":"Select account"}</option>{parties.map(p=><option key={p._id} value={p._id}>{p[category==="customer"?"customer_name":"supplier_name"]}</option>)}</select></Field><Field label="From Date"><input type="date" value={dateFrom} onChange={e=>{setDateFrom(e.target.value);setData(null)}} className="report-input"/></Field><Field label="To Date"><input type="date" value={dateTo} onChange={e=>{setDateTo(e.target.value);setData(null)}} className="report-input"/></Field><div className="flex items-end"><Button icon={Search} onClick={generate} disabled={loading||partiesLoading} className="w-full lg:w-auto">{loading?"Generating...":"Generate"}</Button></div></div>{error&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800"><AlertTriangle size={16}/>{error}</div>}</section>
  {!data&&!loading&&<section className="mt-5 flex min-h-64 flex-col items-center justify-center rounded-3xl border border-dashed border-gray-300 bg-white/60 p-8 text-center"><div className="rounded-2xl bg-gray-100 p-4"><FileText className="text-gray-400"/></div><p className="mt-4 text-sm font-semibold text-gray-700">Statement preview will appear here</p><p className="mt-1 max-w-md text-xs text-gray-400">Select customer or supplier, optionally choose dates, then generate the report.</p></section>}
  {loading&&<div className="mt-5 flex min-h-64 items-center justify-center gap-2 rounded-3xl border border-gray-200 bg-white text-sm text-gray-500"><Loader2 size={18} className="animate-spin"/> Preparing statement...</div>}
  {data&&<section className="mt-5 overflow-hidden rounded-3xl border border-gray-300 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-gray-200 px-5 py-4"><div><p className="text-sm font-bold text-gray-900">Statement Preview</p><p className="text-xs text-gray-500">{selected?.[category==="customer"?"customer_name":"supplier_name"]} · {data.period?.full_statement?"Full statement":"Selected period"}</p></div><div className="flex gap-2"><Button outline icon={Printer} onClick={print}>Print</Button><Button icon={FileDown} onClick={exportPdf}>Export PDF</Button></div></div><div className="grid grid-cols-2 gap-px bg-gray-200 border-b border-gray-200 sm:grid-cols-4"><Quick label="Opening" value={data.opening_balance}/><Quick label="Debit" value={data.totals?.debit}/><Quick label="Credit" value={data.totals?.credit}/><Quick label="Closing" value={data.closing_balance}/></div><div className="statement-preview-stage overflow-auto bg-gray-100 p-4 sm:p-8"><div ref={paperRef} className="mx-auto w-[210mm] min-h-[297mm] max-w-none bg-white p-[12mm] shadow-xl"><StatementPaper data={data} type={category}/></div></div></section>}
  </div><style>{`.report-input{width:100%;height:42px;border:1px solid #d1d5db;border-radius:12px;background:#fff;padding:0 12px;font-size:14px;color:#374151;outline:none}.report-input:focus{border-color:#1C7773;box-shadow:0 0 0 3px rgba(28,119,115,.1)}@media print{body *{visibility:hidden!important}.statement-paper,.statement-paper *{visibility:visible!important}.statement-paper{position:absolute!important;left:0;top:0;width:100%!important;padding:0!important}.statement-paper table{page-break-inside:auto}.statement-paper tr{page-break-inside:avoid;page-break-after:auto}@page{size:A4 portrait;margin:12mm}}`}</style></div>;
}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-600">{label}</span>{children}</label>}
function Quick({label,value}){return <div className="bg-white px-5 py-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-gray-400">{label}</p><p className="mt-1 text-sm font-bold text-gray-800">{money(value)}</p></div>}
