import React, { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Settings, LogOut, ChevronDown, Keyboard, DatabaseBackup, HardDrive, SlidersHorizontal } from 'lucide-react';
import SidebarNavItem from './SidebarNavItem';
import useAuth from '../hooks/useAuth';
import { AnimatePresence } from "framer-motion";
import { fetchMyInvoiceCounter, fetchMyReferenceData, fetchMyRuleData } from '../api/business';
import { BUSINESS_ACCESS_ITEMS, hasAccessForRole } from '../utils/accessConfig';
import { getModuleMeta, MENU_MODULE } from '../config/modules';

const SidebarNav = ({ currentPath, handleLogout, isMobileOpen = false, onCloseMobile }) => {
  const { user } = useAuth(); const navigate = useNavigate(); const [isDropdownOpen, setIsDropdownOpen] = useState(false); const [referenceData, setReferenceData] = useState(null); const [ruleData, setRuleData] = useState(null); const dropdownRef = useRef(null); const prefetchedRoutesRef = useRef(new Set());
  useEffect(() => { const fn = (event) => { if (dropdownRef.current && !dropdownRef.current.contains(event.target)) setIsDropdownOpen(false); }; document.addEventListener('mousedown', fn); return () => document.removeEventListener('mousedown', fn); }, []);
  useEffect(() => { if (!user || user.role === "developer") { setReferenceData(null); setRuleData(null); return; } let mounted = true; Promise.all([fetchMyReferenceData(), fetchMyRuleData()]).then(([r, d]) => { if (mounted) { setReferenceData(r?.reference_data || {}); setRuleData(d?.rule_data || {}); } }).catch(() => { if (mounted) { setReferenceData(null); setRuleData(null); } }); return () => { mounted = false; }; }, [user]);
  const accessReady = user?.role === "developer" || Boolean(referenceData && ruleData);
  const MenuIcon = MENU_MODULE.icon; let navItems = [{ id: 'menu', icon: <MenuIcon className="w-4.5 h-4.5" />, label: MENU_MODULE.label, path: MENU_MODULE.path }];
  if (user.role !== "developer" && accessReady) navItems = navItems.concat(BUSINESS_ACCESS_ITEMS.filter((item) => item.show_in_sidebar && hasAccessForRole(ruleData, referenceData, item.key, user.role)).map((item) => { const Icon = getModuleMeta(item.key).icon; return { id: item.key, icon: <Icon className="w-4.5 h-4.5" />, label: item.label, path: item.path }; }));
  else if (user.role === "developer") navItems = navItems.concat(BUSINESS_ACCESS_ITEMS.filter((item) => ['dashboard', 'users_manage'].includes(item.key)).map((item) => { const Icon = getModuleMeta(item.key).icon; return { id: item.key, icon: <Icon className="w-4.5 h-4.5" />, label: item.label, path: item.path }; }));
  const canSettings = user.role === "developer" || Boolean(accessReady && hasAccessForRole(ruleData, referenceData, "settings", user.role)); const canShortcuts = user.role === "developer" || Boolean(accessReady && hasAccessForRole(ruleData, referenceData, "keyboard_shortcuts", user.role)); const canOptions = user.role === "developer" || Boolean(accessReady && hasAccessForRole(ruleData, referenceData, "options", user.role)); const canSystem = user.role === "developer" || user.role === "admin"; const canBackup = canSystem;
  const active = (path) => path && (currentPath === path || currentPath.startsWith(path + '/')); const initials = (name) => !name ? '?' : name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2); const handleNav = (path) => { navigate(path); if (onCloseMobile) onCloseMobile(); }; const action = (fn) => { setIsDropdownOpen(false); fn(); };
  const prefetchRoute = (path) => { if (!path || prefetchedRoutesRef.current.has(path)) return; prefetchedRoutesRef.current.add(path); const run = async () => { switch (path) { case '/dashboard': { const { fetchDashboardTrend } = await import('../api/dashboard'); const now = new Date(); const dateTo = now.toISOString().slice(0,10); now.setDate(now.getDate()-29); await fetchDashboardTrend({ date_from: now.toISOString().slice(0,10), date_to: dateTo }); break; } case '/invoices': { const api = await import('../api/invoice'); await Promise.allSettled([api.fetchInvoices({page:1,limit:20}), api.fetchInvoiceOrderGroups({page:1,limit:20}), fetchMyInvoiceCounter()]); break; } case '/settings': await Promise.allSettled([fetchMyReferenceData(), fetchMyRuleData()]); break; default: break; } }; if (window.requestIdleCallback) window.requestIdleCallback(() => run().catch(() => {}), { timeout: 1200 }); else window.setTimeout(() => run().catch(() => {}), 120); };
  const mobileClasses = `fixed inset-y-0 left-0 z-40 w-[280px] p-4 transition-transform duration-200 ease-out ${isMobileOpen ? "translate-x-0" : "-translate-x-full"} lg:static lg:translate-x-0 lg:w-78 lg:p-6`;
  const DropdownButton = ({ show, icon: Icon, label, path }) => show ? <button onClick={() => action(() => handleNav(path))} onMouseEnter={() => prefetchRoute(path)} className="w-full flex items-center gap-3 px-3 py-2.5 hover:bg-gray-200/60 text-left rounded-xl cursor-pointer"><Icon className="w-4 h-4 text-gray-600" /><span className="text-sm text-gray-700">{label}</span></button> : null;
  return <aside className={`${mobileClasses} h-full lg:h-screen no-default-transition`}><div className="bg-[#f8faf9] p-4 flex flex-col gap-4 h-full border border-gray-300 rounded-3xl shadow-[0_8px_30px_rgba(28,119,115,0.06)]"><div className="flex items-center gap-1.5 ps-3 pt-2.5 pb-5 border-b border-gray-200"><div className="h-9 w-9 shrink-0 overflow-hidden"><img src="/android-chrome-192x192.png" alt="" className="h-full w-full object-contain" /></div><div className="min-w-0"><h1 className="text-[1.22rem] font-semibold tracking-wide text-[#1C7773]">TexTradeOS PRO</h1><p className="mt-0.5 text-[10px] font-medium uppercase tracking-[0.12em] text-gray-400">A Product of SparkPair</p></div></div><div className="flex flex-col justify-between h-full min-h-0"><nav className="space-y-1 overflow-y-auto pr-1">{navItems.map(item => <SidebarNavItem key={item.id} icon={item.icon} label={item.label} isActive={active(item.path)} onClick={() => handleNav(item.path)} onMouseEnter={() => prefetchRoute(item.path)} onFocus={() => prefetchRoute(item.path)} />)}</nav><div className="pt-3 border-t border-gray-200" ref={dropdownRef}><div className="relative"><button onClick={() => setIsDropdownOpen(!isDropdownOpen)} className="w-full flex items-center gap-3 px-3 py-3 rounded-xl hover:bg-teal-50"><div className="w-8 h-8 rounded-full bg-[#1C7773] flex items-center justify-center text-white font-medium text-sm">{initials(user.name)}</div><div className="flex-1 text-left"><p className="text-sm font-medium text-gray-900">{user.name || 'User'}</p><p className="text-xs text-gray-500 capitalize">{user.role}</p></div><ChevronDown className={`w-4 h-4 text-gray-500 transition-transform ${isDropdownOpen ? 'rotate-180' : ''}`} /></button><AnimatePresence>{isDropdownOpen && <div className="absolute bottom-full left-0 right-0 mb-2 bg-white border border-gray-300 rounded-2xl shadow-lg overflow-hidden no-default-transition"><div className="p-2"><DropdownButton show={canSettings} icon={Settings} label="Settings" path="/settings" /><DropdownButton show={canSystem} icon={HardDrive} label="System Management" path="/system-management" /><DropdownButton show={canBackup} icon={DatabaseBackup} label="Backup" path="/backup" /><DropdownButton show={canOptions} icon={SlidersHorizontal} label="Options & Configuration" path="/options" /><DropdownButton show={canShortcuts} icon={Keyboard} label="Keyboard Shortcuts" path="/keyboard-shortcuts" /><div className="h-px bg-gray-300 my-1.5" /><button onClick={() => action(handleLogout)} className="w-full flex items-center gap-3 px-3 py-2.5 hover:bg-red-50 text-left rounded-xl cursor-pointer"><LogOut className="w-4 h-4 text-red-600" /><span className="text-sm text-red-600 font-medium">Logout</span></button></div></div>}</AnimatePresence></div></div></div></div></aside>;
};
export default SidebarNav;
