import { Activity, CheckCircle2, Database, Download, FileKey2, HardDrive, RefreshCcw, Server, Shield, Upload, Wifi } from "lucide-react";
import { createElement, useEffect, useState } from "react";
import Button from "./Button";
import { IS_DEVELOPMENT } from "../config/environment";
import { useToast } from "../context/ToastContext";
import { fetchSystemCommand, fetchSystemDiagnostics, fetchSystemStatus, fetchSetupCommand, requestSystemCommand, requestUpdateInstall, waitForCommand } from "../api/system";
import { handOffUpdateToLauncher } from "../utils/updateHandoff";
const formatBytes = (value) => { const bytes = Number(value || 0); if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 ** 2) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1024 ** 2).toFixed(1)} MB`; };
export default function SystemManagement() {
 const { showToast }=useToast(); const [status,setStatus]=useState(null); const [busy,setBusy]=useState(""); const [refreshing,setRefreshing]=useState(false);
 const refresh=async()=>{setRefreshing(true);try{const{data}=await fetchSystemStatus();setStatus(data);}catch(error){showToast({type:"error",message:error?.response?.data?.message||"Failed to refresh system status"});}finally{setRefreshing(false);}}; useEffect(()=>{refresh();},[]);
 const runCommand=async(type,payload={})=>{if(busy)return;setBusy(type);try{const{data}=await requestSystemCommand(type,payload);await waitForCommand(fetchSystemCommand,data.id,45000);await refresh();showToast({type:"success",message:`${type[0].toUpperCase()}${type.slice(1)} completed`});}catch(error){showToast({type:"error",message:error?.response?.data?.message||error.message});}finally{setBusy("");}};
 const importLicense=async(event)=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;setBusy("license");try{const document=JSON.parse(await file.text());const response=await fetch("/api/setup/license",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(document)});const command=await response.json();if(!response.ok)throw new Error(command.message||"License import failed");await waitForCommand(fetchSetupCommand,command.id);await refresh();showToast({type:"success",message:"License installed"});}catch(error){showToast({type:"error",message:error.message});}finally{setBusy("");}};
 const installUpdate=async()=>{setBusy("update");try{await requestUpdateInstall();handOffUpdateToLauncher();}catch(error){showToast({type:"error",message:error?.response?.data?.message||"Update failed"});}finally{setBusy("");}};
 const downloadDiagnostics=async()=>{setBusy("diagnostics");try{const{data}=await fetchSystemDiagnostics();const url=URL.createObjectURL(data);const link=document.createElement("a");link.href=url;link.download="TexTradeOS-PRO-Diagnostics.json";document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}catch{showToast({type:"error",message:"Could not prepare diagnostics"});}finally{setBusy("");}};
 const update=status?.update?.update;
 return <div className="space-y-4"><section className="overflow-hidden rounded-3xl border border-gray-300 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-gray-200 bg-gray-50 px-5 py-4 sm:px-6"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl border border-gray-200 bg-white text-gray-600"><HardDrive size={17}/></span><div><h2 className="text-sm font-semibold text-gray-800">System Overview</h2><p className="mt-0.5 text-xs text-gray-400">Live installation and runtime information.</p></div></div><Button outline icon={RefreshCcw} size="sm" loading={refreshing} disabled={refreshing||Boolean(busy)} onClick={refresh}>Refresh Status</Button></div><div className={`grid gap-3 p-5 sm:p-6 ${IS_DEVELOPMENT?"md:grid-cols-3":"md:grid-cols-4"}`}><InfoCard icon={CheckCircle2} label="Service" value={status?"Online":"Checking..."}/><InfoCard icon={Database} label="Database" value={formatBytes(status?.databaseSize)}/>{!IS_DEVELOPMENT&&<InfoCard icon={FileKey2} label="License" value={status?.license?.allowed?status.license.customer:status?.license?.message||"Checking..."}/>}<InfoCard icon={Server} label="Version" value={status?.version||"Checking..."}/></div></section>
 <div className={`grid gap-4 ${IS_DEVELOPMENT?"lg:grid-cols-2":"lg:grid-cols-3"}`}><ActionPanel title="Network & LAN" icon={Wifi} description="Prepare this PC for browser access from devices on the local network."><div className="flex flex-wrap gap-2"><Button size="sm" outline icon={Shield} loading={busy==="firewall"} disabled={Boolean(busy)&&busy!=="firewall"} onClick={()=>runCommand("firewall")}>Configure Firewall</Button><Button size="sm" outline icon={Download} loading={busy==="diagnostics"} disabled={Boolean(busy)&&busy!=="diagnostics"} onClick={downloadDiagnostics}>Download Diagnostics</Button></div><p className="text-xs text-gray-400">LAN browser port: <span className="font-medium text-gray-600">8080</span></p></ActionPanel>
 <ActionPanel title="Health & Diagnostics" icon={Activity} description="Quickly verify the app runtime and export technical details when support or troubleshooting is needed."><div className="grid grid-cols-2 gap-2"><StatusItem label="Application" value={status?"Running":"Checking"} ok={Boolean(status)}/><StatusItem label="Database" value={status?.databaseSize!=null?"Connected":"Checking"} ok={status?.databaseSize!=null}/></div><div className="flex flex-wrap gap-2"><Button size="sm" outline icon={RefreshCcw} loading={refreshing} disabled={refreshing||Boolean(busy)} onClick={refresh}>Run Health Check</Button><Button size="sm" outline icon={Download} loading={busy==="diagnostics"} disabled={Boolean(busy)&&busy!=="diagnostics"} onClick={downloadDiagnostics}>Export Report</Button></div></ActionPanel>
 {!IS_DEVELOPMENT&&<ActionPanel title="Updates" icon={RefreshCcw} description="Keep the installed TexTradeOS PRO runtime on the latest approved release."><div className="rounded-xl border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm text-gray-600">{update?`Version ${update.version} is ready to install.`:"This installation is up to date."}</div>{update&&<Button size="sm" icon={Download} loading={busy==="update"} disabled={Boolean(busy)&&busy!=="update"} onClick={installUpdate}>Install {update.version}</Button>}</ActionPanel>}</div>
 {!IS_DEVELOPMENT&&<section className="overflow-hidden rounded-3xl border border-gray-300 bg-white"><div className="border-b border-gray-200 bg-gray-50 px-5 py-4 sm:px-6"><h2 className="text-sm font-semibold text-gray-800">License Management</h2><p className="mt-0.5 text-xs text-gray-400">Machine fingerprint and replacement license tools.</p></div><div className="flex flex-wrap gap-2 p-5 sm:p-6"><a href="/api/setup/fingerprint" download className="inline-flex min-h-9 items-center gap-2 rounded-xl border border-gray-300 bg-white px-3 text-sm font-medium text-gray-700 hover:bg-gray-50"><Download size={15}/>Download Fingerprint</a><label className={`inline-flex min-h-9 items-center gap-2 rounded-xl border border-gray-300 bg-white px-3 text-sm font-medium text-gray-700 ${busy?"cursor-not-allowed opacity-60":"cursor-pointer hover:bg-gray-50"}`}><Upload size={15}/>{busy==="license"?"Importing License...":"Import Replacement License"}<input type="file" accept=".json" className="hidden" onChange={importLicense} disabled={Boolean(busy)}/></label></div></section>}</div>;
}
function InfoCard({icon,label,value}){return <div className="rounded-2xl border border-gray-200 bg-gray-50/70 p-4"><span className="grid h-9 w-9 place-items-center rounded-xl border border-gray-200 bg-white text-teal-700">{createElement(icon,{size:18})}</span><p className="mt-3 text-[11px] font-medium uppercase tracking-wide text-gray-400">{label}</p><p className="mt-1 truncate text-sm font-semibold text-gray-800">{value}</p></div>;}
function StatusItem({label,value,ok}){return <div className="rounded-xl border border-gray-200 bg-gray-50 px-3 py-2.5"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${ok?"bg-emerald-500":"bg-gray-300"}`}/><span className="text-xs font-medium text-gray-700">{label}</span></div><p className="mt-1 pl-4 text-xs text-gray-400">{value}</p></div>;}
function ActionPanel({title,icon,description,children}){return <section className="flex min-h-52 flex-col rounded-3xl border border-gray-300 bg-white p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl border border-gray-200 bg-gray-50 text-gray-600">{createElement(icon,{size:17})}</span><h2 className="text-sm font-semibold text-gray-800">{title}</h2></div><p className="mt-3 text-sm leading-5 text-gray-500">{description}</p><div className="mt-auto flex flex-col gap-3 pt-5">{children}</div></section>;}
