import { lazy, Suspense, useEffect } from "react";
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import AuthProvider from './context/AuthContext';
import ProtectedRoute from './routes/ProtectedRoute';
import RoleRoute from './routes/RoleRoute';
import Layout from './layouts/layout';
import { ToastProvider } from './context/ToastContext';
import Login from './pages/Login';

const MenuPage = lazy(() => import("./pages/Menu")); const Dashboard = lazy(() => import("./pages/Dashboard")); const Customers = lazy(() => import("./pages/Customers")); const Suppliers = lazy(() => import("./pages/Suppliers")); const Invoices = lazy(() => import("./pages/Invoices")); const Inventory = lazy(() => import("./pages/Inventory")); const Purchases = lazy(() => import("./pages/Purchases")); const Users = lazy(() => import("./pages/Users")); const Settings = lazy(() => import("./pages/Settings")); const Backup = lazy(() => import("./pages/Backup")); const KeyboardShortcuts = lazy(() => import("./pages/KeyboardShortcuts")); const Setup = lazy(() => import("./pages/Setup")); const Returns = lazy(() => import("./pages/Returns")); const SystemManagement = lazy(() => import("./pages/SystemManagement")); const Options = lazy(() => import("./pages/Options"));
const NEGATIVE_NUMBER_REGEX = /^\(?\s*(?:PKR|RS\.?)?\s*-\s*\d[\d,]*(?:\.\d+)?\s*\)?$/i; const NEGATIVE_NUMBER_CLASS = "is-negative-number"; const NON_NEGATIVE_TAGS = new Set(["INPUT", "TEXTAREA", "OPTION", "SCRIPT", "STYLE"]);

export default function App() {
  useEffect(() => { let rafId = 0; const pendingElements = new Set(); const update = (element) => { if (!(element instanceof Element) || NON_NEGATIVE_TAGS.has(element.tagName)) return; const text = Array.from(element.childNodes).filter((node) => node.nodeType === Node.TEXT_NODE).map((node) => node.nodeValue || "").join(" ").trim().replace(/\s+/g, " "); element.classList.toggle(NEGATIVE_NUMBER_CLASS, Boolean(text) && NEGATIVE_NUMBER_REGEX.test(text)); }; const flush = () => { pendingElements.forEach(update); pendingElements.clear(); rafId = 0; }; const queue = (element) => { if (!(element instanceof Element)) return; pendingElements.add(element); if (rafId) cancelAnimationFrame(rafId); rafId = requestAnimationFrame(flush); }; const root = document.getElementById("root"); if (!root) return undefined; queue(root); root.querySelectorAll("*").forEach((el) => pendingElements.add(el)); rafId = requestAnimationFrame(flush); const observer = new MutationObserver((mutations) => { mutations.forEach((mutation) => { if (mutation.type === "characterData") return queue(mutation.target.parentElement); if (mutation.target instanceof Element) queue(mutation.target); mutation.addedNodes.forEach((node) => { if (node instanceof Element) { queue(node); node.querySelectorAll("*").forEach((el) => pendingElements.add(el)); } }); }); if (!rafId && pendingElements.size) rafId = requestAnimationFrame(flush); }); observer.observe(root, { childList: true, subtree: true, characterData: true }); return () => { if (rafId) cancelAnimationFrame(rafId); observer.disconnect(); }; }, []);
  useEffect(() => { const blocked = new Set(["checkbox", "radio", "file", "date", "month", "time", "datetime-local", "color", "range", "button", "submit", "reset", "image", "hidden"]); const handler = (event) => { const target = event.target; if (!(target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement) || target.hasAttribute("data-no-auto-select") || target.disabled || target.readOnly || (target instanceof HTMLInputElement && blocked.has(String(target.type || "").toLowerCase()))) return; requestAnimationFrame(() => { if (document.activeElement === target && String(target.value || "")) try { target.select(); } catch {} }); }; document.addEventListener("focusin", handler, true); return () => document.removeEventListener("focusin", handler, true); }, []);
  const fallback = <div className="min-h-screen flex items-center justify-center text-sm text-gray-500">Loading...</div>;
  return <BrowserRouter future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><ToastProvider><AuthProvider><Suspense fallback={fallback}><Routes><Route path="/login" element={<Login />} /><Route path="/setup" element={<Setup />} /><Route element={<ProtectedRoute><Layout /></ProtectedRoute>}><Route path="/" element={<MenuPage />} /><Route path="/dashboard" element={<Dashboard />} /><Route path="/users" element={<RoleRoute allow={["developer"]} accessKey="users_manage"><Users /></RoleRoute>} /><Route path="/settings" element={<RoleRoute accessKey="settings"><Settings /></RoleRoute>} /><Route path="/system-management" element={<RoleRoute allow={["developer", "admin"]}><SystemManagement /></RoleRoute>} /><Route path="/backup" element={<RoleRoute allow={["developer", "admin"]}><Backup /></RoleRoute>} /><Route path="/options" element={<RoleRoute accessKey="options"><Options /></RoleRoute>} /><Route path="/customers" element={<RoleRoute accessKey="customers"><Customers /></RoleRoute>} /><Route path="/suppliers" element={<RoleRoute accessKey="suppliers"><Suppliers /></RoleRoute>} /><Route path="/purchases" element={<RoleRoute accessKey="purchases"><Purchases /></RoleRoute>} /><Route path="/inventory" element={<RoleRoute accessKey="inventory"><Inventory /></RoleRoute>} /><Route path="/sales-returns" element={<RoleRoute accessKey="sales_returns"><Returns type="sales" /></RoleRoute>} /><Route path="/purchase-returns" element={<RoleRoute accessKey="purchase_returns"><Returns type="purchase" /></RoleRoute>} /><Route path="/invoices" element={<RoleRoute accessKey="invoices"><Invoices /></RoleRoute>} /><Route path="/keyboard-shortcuts" element={<RoleRoute accessKey="keyboard_shortcuts"><KeyboardShortcuts /></RoleRoute>} /></Route><Route path="*" element={<Login />} /></Routes></Suspense></AuthProvider></ToastProvider></BrowserRouter>;
}
